CREATE TABLE towPaperDrafts (
  towId INTEGER PRIMARY KEY REFERENCES tows(id) ON DELETE CASCADE,
  state TEXT NOT NULL,
  revision INTEGER NOT NULL DEFAULT 1,
  updatedBy INTEGER REFERENCES users(id) ON DELETE SET NULL,
  updatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
